"""empty message

Revision ID: 1db5db69f7e5
Revises: 
Create Date: 2024-08-30 10:41:44.997520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1db5db69f7e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_items', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Customer_Details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('pick_up_time', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MenuItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('img_path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Burger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Coffee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Snack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Wine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Wine')
    op.drop_table('Snack')
    op.drop_table('Coffee')
    op.drop_table('Burger')
    op.drop_table('Beer')
    op.drop_table('MenuItems')
    op.drop_table('Customer_Details')
    op.drop_table('Carts')
    # ### end Alembic commands ###
