"""empty message

Revision ID: 3de9c9b307d5
Revises: 6a9e0b9db7d2
Create Date: 2024-08-21 22:27:50.951070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de9c9b307d5'
down_revision = '6a9e0b9db7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MenuItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.drop_column('descrption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MenuItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrption', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
