"""empty message

Revision ID: 66767fb89588
Revises: 7b9a2f44cf10
Create Date: 2024-08-26 23:10:10.235220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66767fb89588'
down_revision = '7b9a2f44cf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_items', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Carts')
    # ### end Alembic commands ###
