"""empty message

Revision ID: 6a9e0b9db7d2
Revises: 894b5df26560
Create Date: 2024-08-21 22:24:55.198307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9e0b9db7d2'
down_revision = '894b5df26560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Burger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Coffee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Snack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Wine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Food')
    with op.batch_alter_table('MenuItems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MenuItems', schema=None) as batch_op:
        batch_op.drop_column('img_path')

    op.create_table('Food',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('specialty', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], name='Food_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Food_pkey')
    )
    op.drop_table('Wine')
    op.drop_table('Snack')
    op.drop_table('Coffee')
    op.drop_table('Burger')
    op.drop_table('Beer')
    # ### end Alembic commands ###
