"""empty message

Revision ID: 7b9a2f44cf10
Revises: 3de9c9b307d5
Create Date: 2024-08-21 22:36:31.497922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9a2f44cf10'
down_revision = '3de9c9b307d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Beer', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    with op.batch_alter_table('Burger', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    with op.batch_alter_table('Coffee', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    with op.batch_alter_table('Wine', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Wine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('Coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('Burger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('Beer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
