"""empty message

Revision ID: 894b5df26560
Revises: 8f8f99389039
Create Date: 2024-08-21 22:05:23.468665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894b5df26560'
down_revision = '8f8f99389039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MenuItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('descrption', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['MenuItems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('menu_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descrption', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='menu_items_pkey')
    )
    op.drop_table('Food')
    op.drop_table('MenuItems')
    # ### end Alembic commands ###
